### ISSUE TITLE
Theme broken?

### ISSUE THREAD

**Issue by nathanoy** [SyndiShanX/Discord-Dark#1]
the theme looks like this for me:
![image](https://user-images.githubusercontent.com/89805394/179263460-4e6dc0ec-d0f1-41be-aead-1820bc1d81e8.png)

have i done something wrong, or is the theme itself broken with the current discord version?

**Comment by SyndiShanX** [comment]
This is a problem on BetterDiscords' end, they haven't updated which version gets downloaded from the site for some reason, if you grab the latest one from here it will work perfectly.
[Latest Version](https://raw.githubusercontent.com/SyndiShanX/Discord-Dark/main/discorddark.theme.css)

**Comment by nathanoy** [comment]
thank you for this fast reply!
works like a charm <3

may i suggest adding a little note somewhere on this github?

**Comment by SyndiShanX** [comment]
I had them update the site, and I also added it to the theme update notification
