### ISSUE TITLE
Modal not matching theme

### ISSUE THREAD

**Issue by VillainsRule** [SyndiShanX/Discord-Dark#10]
Such a minor issue, though great theme.
Thanks for supplying!

<img width="972" alt="Screen Shot 2023-04-25 at 5 44 31 PM" src="https://user-images.githubusercontent.com/101288516/234411203-d6c23890-f4f9-4d42-a32b-5280e09f2d29.png">

**Comment by SyndiShanX** [comment]
Thanks for Reporting, I’ll fix it tomorrow

**Comment by SyndiShanX** [comment]
I fixed the first one, but I can't get that second one to show up

**Comment by SyndiShanX** [comment]
Yeah, if you can get the class names of that box I can add it

**Comment by SyndiShanX** [comment]
Should all be fixed now, thanks for Reporting
