### ISSUE TITLE
AutoMod modal not in theme

### ISSUE THREAD

**Issue by VillainsRule** [SyndiShanX/Discord-Dark#11]
<img width="1019" alt="Screen Shot 2023-04-28 at 9 36 46 PM" src="https://user-images.githubusercontent.com/101288516/235277531-3d157f26-4a11-4f11-912a-504748584e7a.png">
Unless I'm wrong, part of this modal doesn't fit the theme. (it looks like default)
Thanks for the help!

**Comment by SyndiShanX** [comment]
It was default, should be fixed now, thanks for Reporting
