### ISSUE TITLE
Channel notifications

### ISSUE THREAD

**Issue by jaaneh** [SyndiShanX/Discord-Dark#12]
Hey,

Whenever a channel you're not currently watching has a new message, the notification isn't working as expected. Usually the channel name is bold text. Not sure if something else is also missing

![image](https://github.com/SyndiShanX/Discord-Dark/assets/27323317/f3d3e607-efcd-4a8e-9d7c-c34e722d88d3)

**Comment by SyndiShanX** [comment]
Yeah, the classname changed, I was holding off on updating hoping that the WIP BD Update would be pushed to Stable, but I guess I'll stash those changes for now and push an update

**Comment by jaaneh** [comment]
I see. I'm using Vencord, so not sure if that would still be solved with BD updating

**Comment by SyndiShanX** [comment]
The update I mentioned is for the Upcoming BD Var Settings, but the Channels should be fixed now

**Comment by jaaneh** [comment]
Much appreciated. Love this theme. Thanks for keeping it updated.
