### ISSUE TITLE
Discord Main Title Bar Issue

### ISSUE THREAD

**Issue by ShardusBlunder** [SyndiShanX/Discord-Dark#13]
Unable to drag the discord window because it seems that the UI that I interact with is either not there or too small. The most that I can do when interacting with the bar of the window is resize the window. This only happens when using this Theme. I enjoy how the theme looks however this error causes me to be unable to use the theme. 

(I understand my jargon or lingo used may not be fully correct. I'm not that experienced with coding.) I Believe the area I am talking about is called the Title Bar. The image below shows what I mean. 

![Discord_Window_Drag_problem](https://github.com/SyndiShanX/Discord-Dark/assets/110431568/18239620-35fb-4a70-bd49-87c1d93fd06a)

**Comment by SyndiShanX** [comment]
Yeah, this has been a thing for a while, I'll make it larger and add a variable so you can change the size easily

**Comment by SyndiShanX** [comment]
Should be Fixed now, Thanks for Reporting :)
