### ISSUE TITLE
How can I Remove the title bar or move the - [] X to the title bar

### ISSUE THREAD

**Issue by gun4qmm7h** [SyndiShanX/Discord-Dark#16]
![image](https://github.com/SyndiShanX/Discord-Dark/assets/74073434/3ca73515-f729-440e-92db-675368c7f1db)

**Comment by SyndiShanX** [comment]
If you mean the light bar on top, you can change the height with the `--titlebar-height` variable on line 80, if you set that to `0px` it will be gone along with your ability to drag the window around
