### ISSUE TITLE
Show Chat Icon misaligned

### ISSUE THREAD

**Issue by Neko14789** [SyndiShanX/Discord-Dark#18]
The Show Chat Icon Option in the Top right when in a Voice Channel is misaligned to the top

**Comment by Neko14789** [comment]
![image](https://github.com/SyndiShanX/Discord-Dark/assets/25527863/99cf8a74-75ca-4f8e-a820-512788ba6f46)

**Comment by SyndiShanX** [comment]
Should be Fixed, Let me know if it needs further adjustment

**Comment by Neko14789** [comment]
It did work in some cases but not all
![image](https://github.com/SyndiShanX/Discord-Dark/assets/25527863/f8ecfbb8-ebca-43f1-b5dd-3fefc31676bc)

**Comment by SyndiShanX** [comment]
Idk why your buttons are overlapping, mine are all quite spread out
![image](https://github.com/SyndiShanX/Discord-Dark/assets/23367120/88ee074d-ed86-4c19-a3b9-d38626d7f761)

**Comment by SyndiShanX** [comment]
Try completely closing Discord and See if it's fixed, if not let me know

**Comment by Neko14789** [comment]
It is sadly not fixed

**Comment by Neko14789** [comment]
As soon as the "Centered" button appears, it breaks

**Comment by SyndiShanX** [comment]
Hmm, idk how to fix it since I don’t have that issue :/

**Comment by Neko14789** [comment]
![image](https://github.com/SyndiShanX/Discord-Dark/assets/25527863/88046711-f339-46ed-8f92-95225d956a63)
It's okay if I just view the voice channel, but when I join it is misaligned

**Comment by Neko14789** [comment]
No problem, maybe there is some very strange issue with one extension or so

**Comment by SyndiShanX** [comment]
I can’t get it to break on my end, I tried viewing it and joining and it’s fine

Try disabling them real quick

**Comment by Neko14789** [comment]
Real quick he says 
![image](https://github.com/SyndiShanX/Discord-Dark/assets/25527863/95cc1254-9bc8-4fe1-853c-e403470aae77)

**Comment by SyndiShanX** [comment]
You can just move them out of the folder

**Comment by SyndiShanX** [comment]
Might be Bigger Stream Preview just looking at the names, could also be a Vencord thing

**Comment by Neko14789** [comment]
Hm, since it is vencord it did not have a folder but after removing them from config the issue is gone, so it seems to be an extension :(

**Comment by SyndiShanX** [comment]
Ah, not sure if there’s much I can do about that then sadly

**Comment by Neko14789** [comment]
No problem, and sorry for wasting your time a bit there

**Comment by SyndiShanX** [comment]
It’s all good 👍
