### ISSUE TITLE
Show all "members" button is not styled correctly

### ISSUE THREAD

**Issue by Neko14789** [SyndiShanX/Discord-Dark#19]
![image](https://github.com/SyndiShanX/Discord-Dark/assets/25527863/b9b52539-bde0-4e2a-94d3-7e3312a017f6)
This Button, shown when you are in a server and click the hide members without video option in the top tight toolbar, is not correctly styled and thus has this white square border on the button

**Comment by SyndiShanX** [comment]
Do you happen to know the selector for it?

**Comment by Neko14789** [comment]
What do you mean with selector?

**Comment by SyndiShanX** [comment]
The CSS Selector, is there a way to get this to show up on my end by myself?

**Comment by Neko14789** [comment]
Does this help? 
![image](https://github.com/SyndiShanX/Discord-Dark/assets/25527863/79f88788-1718-49bb-85c9-4fb3a180d222)

**Comment by Neko14789** [comment]
Also this looks a bit odd, is this intended?
![image](https://github.com/SyndiShanX/Discord-Dark/assets/25527863/23c64bf5-3839-4db5-b028-493a898b2442)

**Comment by SyndiShanX** [comment]
Let me know if that fixed the button, and what part am I looking at?

**Comment by Neko14789** [comment]
Its the Friends view

**Comment by SyndiShanX** [comment]
Yeah, but what in that image am I looking for?

**Comment by Neko14789** [comment]
it fixed it :D
![image](https://github.com/SyndiShanX/Discord-Dark/assets/25527863/2d511c81-11a6-418b-8d79-01ee5e7f65f5)

**Comment by SyndiShanX** [comment]
The Search Icon Background I'm guessing?

**Comment by Neko14789** [comment]
> Yeah, but what in that image am I looking for?

In the area where it is a lighter shade of gray, it looks a bit misstyled, especially because of the search button. Also, it does not follow the rounded light gray area scheme of areas in the same view.

**Comment by Neko14789** [comment]
> The Search Icon Background I'm guessing?

Yeah, probably the search icon background is making it look odd

**Comment by SyndiShanX** [comment]
Look any better?

![image](https://github.com/SyndiShanX/Discord-Dark/assets/23367120/e3f610e2-e41e-43d7-820f-d0b8428a538d)

**Comment by Neko14789** [comment]
Yeah, Looks already better, If possible you could try slightly rounded Corners similar too how it is on the left where the Friends panel ist selected

**Comment by Neko14789** [comment]
But in General I really Like this Style, Very good Work 👍

**Comment by SyndiShanX** [comment]
Thank you, can you show exactly which part you're talking about, this page has a bit going on
