### ISSUE TITLE
Animations flickering

### ISSUE THREAD

**Issue by nathanoy** [SyndiShanX/Discord-Dark#2]
this doesn't seem intended:
1. that a message "jumps" like that after beeing send.
2. the message, which is replied to, drops down, when pressing on the link to view it.

https://user-images.githubusercontent.com/89805394/179370264-4d67f576-a894-491d-af6f-4e26ef115d34.mp4

**Comment by SyndiShanX** [comment]
I just removed the messages being closer together as I can't tell much of a difference without it
Thanks for reporting :)
