### ISSUE TITLE
Not a real issue or bug just a question: how do I change how Threads are displayed

### ISSUE THREAD

**Issue by daedreaming** [SyndiShanX/Discord-Dark#20]
In normal Discord, Threads that you are subscribed to are always shown, but in this theme Themes collapse until you mouse over them. The problem with this is there's no indicator that a Thread has been posted in and I'm in servers that use Threads judicially so I would like to revert this back to how it works on normal Discord. What CSS changes would I have to make as someone who doesn't know CSS but knows how to edit the theme file if I'm told what to put in.

e: Also while unrelated this is my only issue with this theme and I love it a lot you did great with it!

**Comment by SyndiShanX** [comment]
Yeah, I have the same problems with it, I’ll try to fix it again, if that doesn’t pan out I’ll probably just remove it tomorrow at some point

**Comment by SyndiShanX** [comment]
Should be gone now, I couldn't find a good way of fixing it, thanks for reporting :)
