### ISSUE TITLE
Reverting App Tag to Bot reverts ALL tags to Bot

### ISSUE THREAD

**Issue by iamanerd3** [SyndiShanX/Discord-Dark#21]
I'm using vencord, and have a plugin enabled that shows extra tags for users.
![image](https://github.com/user-attachments/assets/e5405e6c-1ca8-4a77-a33b-08adc055cc40)

The plugin uses the bot text thingie (sorry, idk what it's called) this thing: 
![image](https://github.com/user-attachments/assets/2a47e9c6-0fad-4497-84a5-32a699b530bb)

discord dark theme just changes it ALL to bot, regardless of what the actual text in the tag was.

i was wondering if there is any way to disable that specific functionality in the theme? or just fix the bug. if i wanted to disable the replace app to bot part all together, i can't just edit the theme file since you're importing all the css from this github repo. my solution is make a new main css file, except remove this part:
```
/* Revert App Tag to Bot - Dav */
.botTag_a9e77f:not(.botTagAI_a9e77f, .botTagOP_a9e77f, .botTagRemix_a9e77f, .decorator_c91bad) .botText_a9e77f {
  font-size: 0 !important;
  line-height: 0 !important;
}
```

you could name this alternative file something like discorddark-show-app-tag.css, maybe. then in the theme file i'd change this line
`@import url("https://syndishanx.github.io/Discord-Dark/discorddark.css");`
to
`@import url("https://syndishanx.github.io/Discord-Dark/discorddark-show-app-tag.css");`

**Comment by SyndiShanX** [comment]
~I can add it to the main theme file using vars, I’ll do that later today~

**Comment by SyndiShanX** [comment]
I changed it to an Import, so you should be able to just remove that to fix the issue

**Comment by iamanerd3** [comment]
ok, let me try it
