### ISSUE TITLE
Visual bug of Direct Messages button.

### ISSUE THREAD

**Issue by 194pp** [SyndiShanX/Discord-Dark#3]
Not sure if it's because of my machine, but Direct Messages button is positioned incorrectly.
May have been caused by the `public` button bellow.
Here's a screenshot:
![image](https://user-images.githubusercontent.com/61292534/187801929-8428e213-38bb-4baa-98e0-d2df0c61917c.png)

**Comment by 194pp** [comment]
Stiched up some styling that helps somewhat mitigate this bug until this issue gets fixed (by removing `public` button and adjusting XY offsets a bit).
Custom CSS Editor styles:
```
.tutorialContainer-1pL9QS {
    transform: translate(-4px, -75px) !important;
}

.tutorialContainer-1pL9QS > *:not(:first-child) {
    display: none !important;
}
```

**Comment by SyndiShanX** [comment]
Pushed, thanks
