### ISSUE TITLE
is theme up to date? Some aligment issues etc.

### ISSUE THREAD

**Issue by cobra-7777** [SyndiShanX/Discord-Dark#4]
Hello, i really like the look of this theme. Sadly the server list is very misaligned on my client. And when a user sends me a direct message, their icon is cut off slightly at the top, which annoys me very much :D Are these known issues or is there anything i can do to align the server list correctly?

![image](https://user-images.githubusercontent.com/71074471/189747922-fba2b38f-35db-4275-b3af-9c4d4088e960.png)

thanks!

**Comment by cobra-7777** [comment]
Sorry did not notice there was a scrollbar-width config option. setting the scrollbar to 0px wide gets the server list aligned with the discord menu button. However the clipping of the icon when someone sends a direct message remains a problem for me.

![image](https://user-images.githubusercontent.com/71074471/189750771-afb7ee0a-ef2e-48f4-a2ba-ba861262ed11.png)

**Comment by SyndiShanX** [comment]
Pushed a Fix, thanks for Reporting

**Comment by cobra-7777** [comment]
I hate to reopen, but sadly now the server list is misaligned if you have the scrollbar turned off.
![image](https://user-images.githubusercontent.com/71074471/189953991-075e5f43-aaf9-4764-b73c-bef9246d4c96.png)

If its too much of a hassle i can just re-enable the scrollbar. I just really think the theme looks a lot cleaner without the scrollbar next to the server list.

The issue with the direct messages is resolved now though, looks great! :)

**Comment by cobra-7777** [comment]
i guess one way to do it could be having an option in the config to set the scrollbar to the same color as the background, thus "removing it" without actually changing the spacing.

**Comment by SyndiShanX** [comment]
I added those to the Config, you'll have to download the theme file from here as it will take a couple days to get approved on BD's end https://raw.githubusercontent.com/SyndiShanX/Discord-Dark/main/discorddark.theme.css

**Comment by cobra-7777** [comment]
> I added those to the Config, you'll have to download the theme file from here as it will take a couple days to get approved on BD's end https://raw.githubusercontent.com/SyndiShanX/Discord-Dark/main/discorddark.theme.css

you are a champion! thanks! really love the theme! :)
