### ISSUE TITLE
Chat looks bad if using compact mode

### ISSUE THREAD

**Issue by Blackwolfe5** [SyndiShanX/Discord-Dark#6]
This would be the one theme I found that I really like, but chat looks kind of odd in compact mode. It's the timestamp and replies that end up looking weird. Looks fine if not using compact mode (I prefer compact though)

![2022-11-25 18_02_17-#Offtopic _ BetterDiscord](https://user-images.githubusercontent.com/40699677/204030411-e9267968-24f7-45cc-b306-e0e7bf7761f7.png)

**Comment by SyndiShanX** [comment]
I’ll have a look at it tomorrow

**Comment by SyndiShanX** [comment]
Should be fixed
