### ISSUE TITLE
Theme issues in inbox

### ISSUE THREAD

**Issue by asorel1942** [SyndiShanX/Discord-Dark#7]
Messages in Inbox use default blurple colors rather than theme colors. Additionally, "mark as read" button for individual channels does not stay at top of inbox as it should, but disappears when scrolling.
![image](https://user-images.githubusercontent.com/33983895/208343411-ae80851f-4004-4642-aa02-f49417c54462.png)
![image](https://user-images.githubusercontent.com/33983895/208343423-edb5e2fb-bff5-4b15-8a8e-eca43c069be8.png)

**Comment by SyndiShanX** [comment]
Fixed, thank you for Reporting :)
